services:
  redis:
    image: redis:latest
    container_name: swapdata_redis
    # You can drop the port if you want socket-only access:
    ports:
      - "6379:6379"
    volumes:
      - ./.data/redis:/data
      - ./run/redis:/var/run/redis     # <â€” host dir mounted where socket will live
    command:
      - redis-server
      - --appendonly
      - "yes"
      - --unixsocket
      - /var/run/redis/redis.sock
      - --unixsocketperm
      - "777"
      - --port
      - "6379"   # or "0" to disable TCP
    restart: unless-stopped
  data:
    build:
      context: ./data
      dockerfile: Dockerfile
    container_name: swapdata_data
    environment:
      - GRPC_ADDR=http://31.172.68.74:10200
    ports:
      - "5000:8080"
    command: ./bin